# Generated by Django 4.2.7 on 2023-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Gram'), (2, 'Litre  '), (3, 'Piece')], default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
